name: Trigger Playwright Tests
on:
  push:
    branches: [ main, develop, staging ]  # Adjust branches as needed
  pull_request:
    branches: [ main, develop ]

jobs:
  trigger-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}
          repository: shriramur/playwrightCopilotFramework
          event-type: dev-code-updated
          client-payload: |
            {
              "ref": "${{ github.ref_name }}",
              "sha": "${{ github.sha }}",
              "repository": "${{ github.repository }}",
              "actor": "${{ github.actor }}"
            }
